---
- name: Vim - Install
  homebrew:
    formula: neovim
    state: present

- name: Ensure .config/nvim directory
  file:
    path: "~/.config/nvim"
    state: directory

- name: Vim - Copy nvim/lua
  file:
    src: "{{ role_path }}/files/lua"
    dest: "~/.config/nvim/lua"
    state: link

- name: Vim - Copy nvim/init.lua
  file:
    src: "{{ role_path }}/files/init.lua"
    dest: "~/.config/nvim/init.lua"
    state: link
