---
- name: Docker - Install CE edition
  homebrew_cask:
    name: docker
    state: installed

- name: Docker - Install autocomplete
  file:
    src: "/Applications/Docker.app/Contents/Resources/etc/{{ item }}.zsh-completion"
    dest: "/usr/local/share/zsh/site-functions/_{{ item }}"
    state: link
  loop:
    - docker
    - docker-machine
    - docker-compose
