vim.keymap.set("n", "<leader>v", "<cmd>e ~/.config/nvim/init.lua<cr>", { desc = "Edit config" })
vim.keymap.set("n", "<C-h>", "<C-w>h", { desc = "Go to Left Window", remap = true })
vim.keymap.set("n", "<C-j>", "<C-w>j", { desc = "Go to Lower Window", remap = true })
vim.keymap.set("n", "<C-k>", "<C-w>k", { desc = "Go to Upper Window", remap = true })
vim.keymap.set("n", "<C-l>", "<C-w>l", { desc = "Go to Right Window", remap = true })
vim.keymap.set("n", "<leader><leader>", "<cmd>e #<cr>", { desc = "Switch to Other Buffer" })
vim.keymap.set("n", "<leader>z", "<cmd>bp<cr>", { desc = "Prev Buffer" })
vim.keymap.set("n", "<leader>x", "<cmd>bn<cr>", { desc = "Next Buffer" })
vim.keymap.set("n", "<leader>w", "<cmd>:bp<cr>:bd#<cr>", { desc = "Delete buffer (keep window)" })
vim.keymap.set("n", "<leader>q", "<cmd>:bd<cr>", { desc = "Delete buffer (close window)" })
vim.keymap.set({"n", "v"}, "<leader>cc", "gcc<esc>", { desc = "Comment code", remap = true })
vim.api.nvim_create_autocmd("FileType", {
  pattern = "*",
  callback = function()
    if vim.bo.buftype == "" then
      vim.keymap.set("n", "<cr>", "<cmd>nohlsearch<cr>", { buffer = true, silent = true })
    end
  end,
})
vim.keymap.set("n", "<leader>o", function()
  vim.fn.system({ "open", "-R", vim.fn.expand("%:p") })
end, { desc = "Reveal in Finder" })
vim.keymap.set("n", "<leader>go", function()
  local file = vim.fn.expand("%:.")
  local line = vim.fn.line(".")
  local remote = vim.fn.trim(vim.fn.system("git remote get-url origin"))
  local branch = vim.fn.trim(vim.fn.system("git rev-parse --abbrev-ref HEAD"))
  remote = remote:gsub("git@github.com:", "https://github.com/"):gsub("%.git$", "")
  vim.fn.system({ "open", remote .. "/blob/" .. branch .. "/" .. file .. "#L" .. line })
end, { desc = "Open on GitHub" })
