if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

source $HOME/.zsh/aliases
source $HOME/.zsh/functions

export fpath=(/usr/local/share/zsh/site-functions $fpath)

export EDITOR='nvim'
export HOMEBREW_NO_ANALYTICS=1
export JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_202.jdk/Contents/Home

# Bash autocomplete compatibility
autoload bashcompinit
bashcompinit
complete -F "ahoy --generate-bash-completion" ahoy

source $HOME/.profile

export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"
export PATH="/usr/local/opt/node@10/bin:$PATH"
export PATH="$HOME/Code/brightmotive/bin:$PATH"
