if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

source $HOME/.zsh/aliases
source $HOME/.zsh/functions

export fpath=(/usr/local/share/zsh/site-functions $fpath)

export EDITOR='nvim'
export HOMEBREW_NO_ANALYTICS=1

# Bash autocomplete compatibility
autoload bashcompinit
bashcompinit

source $HOME/.profile

export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"
export PATH="/usr/local/opt/node@10/bin:$PATH"
export PATH="$HOME/Code/brightmotive/bin:$PATH"
export PATH="$HOME/Library/Python/3.7/bin:$PATH"
