bundleid: net.turbare.switchBluetoothDevice
category: Tools
connections:
  filter_bluetooth:
  - destinationuid: switch_bluetooth
  switch_bluetooth: []
createdby: Akihiro Uchida
description: switch a bluetooth device pairing
disabled: false
name: alfred-switch-bluetooth
objects:
- config:
    argumenttype: 1
    keyword: bluedev
    runningsubtext: filtering bluetooth devices
    script: !include 'filter_bluetooth'
    subtext: Start typing a device name...
    title: Toggle a bluetooth device
  type: alfred.workflow.input.scriptfilter
  uid: filter_bluetooth
- config:
    applescript: !include 'switch_bluetooth'
  type: alfred.workflow.action.applescript
  uid: switch_bluetooth
readme: !include 'README'
uidata:
  filter_bluetooth:
    ypos: 60.0
  switch_bluetooth:
    ypos: 60.0
webaddress: github.com/uchida/alfred-switch-bluetooth
