[general]
import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]

[window]
title = "Terminal"
dynamic_title = true
decorations_theme_variant = "Dark"

[font]
normal = { family = "iMWritingMono Nerd Font", style = "Regular" }
bold = { family = "iMWritingMono Nerd Font", style = "Bold" }
italic = { family = "iMWritingMono Nerd Font", style = "Regular Italic" }
bold_italic = { family = "iMWritingMono Nerd Font", style = "Bold Italic" }
size = 16
offset = { x = 0, y = 8 }

[keyboard]
bindings = [
  { key = "Right", mods = "Alt", chars = "\u001BF" },
  { key = "Left",  mods = "Alt", chars = "\u001BB" },
]
