return {
  "nvim-treesitter/nvim-treesitter",
  build = ":TSUpdate",
  opts_extend = { "ensure_installed" },
  opts =  {
    ensure_installed = { 
      "bash",
      "c",
      "clojure",
      "diff",
      "html",
      "javascript",
      "json",
      "jsonc",
      "lua",
      "luadoc",
      "luap",
      "markdown",
      "markdown_inline",
      "printf",
      "python",
      "query",
      "regex",
      "rust",
      "toml",
      "tsx",
      "typescript",
      "vim",
      "vimdoc",
      "xml",
      "yaml",
    },
    highlight = { enable = true },
    indent = { enable = true },  
  },
  config = function(_, opts)
    require("nvim-treesitter").setup(opts)
  end,
}
