processes:
  elasticsearch:
    command: elasticsearch
    disabled: true
    environment:
      - "ES_JAVA_HOME=/opt/homebrew/opt/openjdk@21/libexec/openjdk.jdk/Contents/Home"

  valkey:
    command: valkey-server
    disabled: true
